### ISSUE TITLE
Create initial Home profile page

### ISSUE THREAD

**Issue by brylie** [GeriLife/caregiving#38]
Create as much of the Home page from the previous GeriLife Wellbeing application as is possible. Open a follow-up ticket for any remaining items.

![image](https://github.com/GeriLife/caregiving/assets/17307/ea5429b3-9752-445c-aa49-1d2c2c1e2d98)

## Sub-issues

This issue is split into the following sub-issues

- [x] #43 
- [ ] #42

**Comment by adrienneli104** [comment]
I'm interested in learning more about this issue. What are the graphs displaying and would I be able to have access to the previous GeriLife Wellbeing application in English?

**Comment by brylie** [comment]
The original application is developed in English and can be found here: https://github.com/GeriLife/wellbeing

The home charts are documented in the JavaScript source code: https://github.com/GeriLife/wellbeing/blob/main/app/server/methods/charts/homeCharts.js

We are porting these charts to Python/Django/SQL.

**Comment by brylie** [comment]
@adrienneli104, I've completed part of this issue today. However, there are two remaining sub-issues you might consider taking:

- #43 
- #42

**Comment by brylie** [comment]
Closing since this issue has been split to separate issues for each page component.
